version: '2'
services:
  web:
    build: .
    ports:
     - "3000:3000"
    environment:
     - ELASTICSEARCH_URL=elasticsearch:9200
     - PORT=3000
    # TODO - cover all relevant js files
    volumes:
     - "./src:/app/src"
     - "./tests:/app/tests"
    networks:
     - front
  elasticsearch:
    image: "elasticsearch:2.4.5"
    networks:
     - front
networks:
  front:
    driver: bridge
